server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always

application:
  sse:
    heartbeat-interval: 15s
    subscriber-remove-delay: 10s
    events:
      heartbeat:
        event-name: PING
        comment: Heartbeat
      start:
        event-name: CONNECT
        comment: Connected
      error:
        event-name: ERROR
        comment: Internal error
      notification:
        event-name: NOTIFICATION
        comment: New event
  redis:
    retry:
      max-attempts: 5
      initial-backoff: 1s
      max-backoff: 30s
      jitter-factor: 0.5
    topics:
      user-id-placeholder: "{userId}"
      user-notification-pattern: notification:user:${application.redis.topics.user-id-placeholder}